apiVersion: v1
kind: Pod
metadata:
  name: hackfest-nginx-flex-blobfuse-pvc
spec:
  containers:
  - name: nginx-flex-blobfuse
    image: nginx
    volumeMounts:
    - name: flexvol-mount
      mountPath: /data
  volumes:
  - name: flexvol-mount
    persistentVolumeClaim:
      claimName: hackfest-pvc-blobfuse-flexvol
