apiVersion: v1
kind: PersistentVolume
metadata:
  name: hackfest-pv-blobfuse-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: azure/blobfuse
    options:
      container: tdhackfestcontainer
      mountoptions: --file-cache-timeout-in-seconds=120
      tmppath: /tmp/blobfuse
    secretRef:
      name: blobfusehackfest
  persistentVolumeReclaimPolicy: Retain